// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UrlCutter.Models;

#nullable disable

namespace UrlCutter.Migrations
{
    [DbContext(typeof(DbUrl))]
    [Migration("20221212132649_InitialCreate1")]
    partial class InitialCreate1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("UrlCutter.Models.URL", b =>
                {
                    b.Property<string>("Token")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("LongUrl")
                        .HasColumnType("text");

                    b.HasKey("Token");

                    b.ToTable("Urls");
                });
#pragma warning restore 612, 618
        }
    }
}
