// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UrlCutter.Models;

#nullable disable

namespace UrlCutter.Migrations
{
    [DbContext(typeof(DbUrl))]
    partial class DbUrlModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("UrlCutter.Models.URL", b =>
            {
                b.Property<string>("Token")
                    .HasColumnType("TEXT");

                b.Property<string>("LongUrl")
                        .HasColumnType("TEXT");

                b.HasKey("Token");

                b.ToTable("Urls");
            });
#pragma warning restore 612, 618
        }
    }
}
