// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UrlCutter.Models;

#nullable disable

namespace UrlCutter.Migrations
{
    [DbContext(typeof(DbUrl))]
    partial class DbUrlModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("UrlCutter.Models.URL", b =>
                {
                    b.Property<string>("Token")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("LongUrl")
                        .HasColumnType("text");

                    b.HasKey("Token");

                    b.ToTable("Urls");
                });
#pragma warning restore 612, 618
        }
    }
}
